#ifndef PROTOTYPE_H
#define PROTOTYPE_H

typedef enum 
{
	PROTO_GET_TOKEN = 0,
	PROTO_USER_BIND,
	PROTO_GET_DEVICES_LIST,
	PROTO_GET_ALARM_MSG,
	PROTO_GET_DEVICE_P2PPORT,
    PROTO_DELETE_ALARM_MSG,
	PROTO_DEVICE_SET,
	PROTO_DEVICE_ADD,
	PROTO_REAL_PLAY,
	PROTO_DEVICE_RECORD_PLAY,
	PROTO_CLOUD_RECORD_PLAY,
    PROTO_RECORDLIST,
    PROTO_PTZ_CTRL,
	PROTO_GET_DEVICE_BYID,
}PROTOTYPE_E;

#endif // PROTOTYPE_H